### ISSUE TITLE
The unit of data value provided in HumanLiverSeurat@data

### ISSUE THREAD

**Issue by lijxug** [BaderLab/HumanLiver#3]
Hi,
I want to know the unit of the data you provided in HuamanLiverSeurat@data so I can run some downstream analysis of my own. Is it log2(TPM + 1) and is it scaled somehow?
Thx.

**Comment by innesbre** [comment]
Data are normalized using the scran pool and deconvolute method (https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0947-7) and in log2(x + 1) space, yes.

Raw counts are in GEO (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE115469) in case you want to do your own normalization.

**Comment by toddajohnson** [comment]
I know that this is a very old question, but since this dataset is now part of the Azimuth single cell human liver reference dataset, it seems appropriate to add a comment.

The csv file on GEO [GSE115469](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE115469)) does not appear to be the raw count data, since the values in this package's HumanLiverSeurat@assays[["RNA"]]@data (HumanLiverData.Rdata file) exactly match those in the GSE115469_Data.csv.gz; so both seem to represent the log normalized values from the scran pool and deconvolute method.  However, while those values are all doubles, those in  HumanLiverSeurat@assays[["RNA"]]@counts are integers and would seem to be the original counts; plus, they match the "total_counts" in HumanLiverSeurat@meta.data which have minimums matching the cutoffs in the paper's methods.
