### ISSUE TITLE
How can I get cell type name?

### ISSUE THREAD

**Issue by chanwkimlab** [BaderLab/HumanLiver#4]
Hello

Firstly, I'd like to thank you for publishing the valuable scRNA seq dataset.

Could you give me advice on identifying the name of cell-types from the Rdata file?

I can see that `load("data/HumanLiver/inst/liver/HumanLiver.RData")` loads two variables, `HumanLiverSeurat` and `sCVdL`, into workspace.

And I found gene-cell matrix is in `HumanLiverSeurat[['RNA']]@data`( in case of raw count, `HumanLiverSeurat[['RNA']]@counts`)

I guess that cluster(or cell type) information is in `HumanLiverSeurat@active.ident`(or `HumanLiverSeurat@meta.data$res.0.8`, which is the same as it) as the number of unique values is 20, which is in line with that of publication.
However, I failed to identify to which cell-types each integer in `active.ident` column corresponds.
(ex.endothelial cells, cholangiocytes, hepatic stellate cells, B cells, etc.)

Could you help me out with this? Am I missing something?
Thank you for your help in advance,

Best regards,
Chanwoo Kim

**Comment by innesbre** [comment]
You are correct in that you can load the data that way.  You can also run `viewHumanLiver()` in an R session, then close the Shiny app, and you'll have those two objects in your workspace.

I realized that I hadn't stored the cluster names in the object, since they're annotated from a list of marker genes when the RShiny app is run.  I've updated the package, so if you reinstall it, you'll find them now using the following code: `ClusterNames(sCVdL$res.0.8)`
And as a bonus, you can see which genes were used as markers for the annotation step using this command: `attr(sCVdL$res.0.8@Clusters,"cellMarkers")`

**Comment by chanwkimlab** [comment]
Thank you so much!
